package cardholders;
// Generated 17.04.2015 15:01:51 by Hibernate Tools 4.3.1



/**
 * ApacseventsCha generated by hbm2java
 */
public class ApacseventsCha  implements java.io.Serializable {


     private String eventid;
     private String eventtype;
     private String eventtypedesc;
     private String holderid;
     private String holdername;
     private String holdershortname;
     private String sourceid;
     private String sourcename;
     private String eventtime;
     private String messagexml;
     private String messageid;
     private String messagetime;

    public ApacseventsCha() {
    }

	
    public ApacseventsCha(String eventid) {
        this.eventid = eventid;
    }
    public ApacseventsCha(String eventid, String eventtype, String eventtypedesc, String holderid, String holdername, String holdershortname, String sourceid, String sourcename, String eventtime, String messagexml, String messageid, String messagetime) {
       this.eventid = eventid;
       this.eventtype = eventtype;
       this.eventtypedesc = eventtypedesc;
       this.holderid = holderid;
       this.holdername = holdername;
       this.holdershortname = holdershortname;
       this.sourceid = sourceid;
       this.sourcename = sourcename;
       this.eventtime = eventtime;
       this.messagexml = messagexml;
       this.messageid = messageid;
       this.messagetime = messagetime;
    }
   
    public String getEventid() {
        return this.eventid;
    }
    
    public void setEventid(String eventid) {
        this.eventid = eventid;
    }
    public String getEventtype() {
        return this.eventtype;
    }
    
    public void setEventtype(String eventtype) {
        this.eventtype = eventtype;
    }
    public String getEventtypedesc() {
        return this.eventtypedesc;
    }
    
    public void setEventtypedesc(String eventtypedesc) {
        this.eventtypedesc = eventtypedesc;
    }
    public String getHolderid() {
        return this.holderid;
    }
    
    public void setHolderid(String holderid) {
        this.holderid = holderid;
    }
    public String getHoldername() {
        return this.holdername;
    }
    
    public void setHoldername(String holdername) {
        this.holdername = holdername;
    }
    public String getHoldershortname() {
        return this.holdershortname;
    }
    
    public void setHoldershortname(String holdershortname) {
        this.holdershortname = holdershortname;
    }
    public String getSourceid() {
        return this.sourceid;
    }
    
    public void setSourceid(String sourceid) {
        this.sourceid = sourceid;
    }
    public String getSourcename() {
        return this.sourcename;
    }
    
    public void setSourcename(String sourcename) {
        this.sourcename = sourcename;
    }
    public String getEventtime() {
        return this.eventtime;
    }
    
    public void setEventtime(String eventtime) {
        this.eventtime = eventtime;
    }
    public String getMessagexml() {
        return this.messagexml;
    }
    
    public void setMessagexml(String messagexml) {
        this.messagexml = messagexml;
    }
    public String getMessageid() {
        return this.messageid;
    }
    
    public void setMessageid(String messageid) {
        this.messageid = messageid;
    }
    public String getMessagetime() {
        return this.messagetime;
    }
    
    public void setMessagetime(String messagetime) {
        this.messagetime = messagetime;
    }




}


